exp: TextClassification

mode: 
    - train

models:
    hf_text_classification_model:
      - JeremiahZ/bert-base-uncased-mnli
      
    

trainfpath: ../final/data/synth-pos_train_new.tsv

validfpath: ../final/data/synth-pos_val_new.tsv

modelfpath: ../final/models/synth_pos_nli

textlabel: text

pairlabel: pair

device: cuda

id2label:
    2: neutral
    1: neutral
    0: entailment