exp: TextClassification

mode: 
    - train

models:
    hf_text_classification_model:
      - JeremiahZ/bert-base-uncased-mnli
      

trainfpath: ../final/data/mono-data_train.tsv

validfpath: ../final/data/mono-data_val.tsv

modelfpath: ../final/models/mono_nli

textlabel: text

pairlabel: pair

device: cuda

id2label:
    2: neutral
    1: neutral
    0: entailment