exp: TextClassification

mode: 
    - train

models:
    hf_text_classification_model:
      - JIWON/bert-base-finetuned-nli
      
trainfpath: ../data/symmetry_training_data.tsv
validfpath: ../data/symmetry_training_data.tsv 

device: cpu

numLabels: 3
modelfpath: ../models/sym_nli

id2label:
    2: contradiction
    1: entailment
    0: neutral